{"context_annotations": [{"domain": {"id": "123", "name": "Ongoing News Story", "description": "Ongoing News Stories like 'Brexit'"}, "entity": {"id": "1220701888179359745", "name": "COVID-19"}}], "author_id": "1110124183", "entities": {"mentions": [{"start": 0, "end": 15, "username": "spectatorindex", "id": "1626294277"}, {"start": 46, "end": 50, "username": "WHO", "id": "14499829"}], "hashtags": [{"start": 78, "end": 86, "tag": "COVID19"}]}, "referenced_tweets": [{"type": "replied_to", "id": "1250731769487257600"}], "id": "1250811929913892866", "lang": "en", "in_reply_to_user_id": "1626294277", "text": "@spectatorindex That\u2019s why someone is blaming @WHO for his failure to contain #COVID19 in time.", "public_metrics": {"retweet_count": 0, "reply_count": 0, "like_count": 0, "quote_count": 0}, "conversation_id": "1250731769487257600", "created_at": "2020-04-16T15:42:57.000Z", "source": "Twitter for iPhone", "reply_settings": "everyone", "possibly_sensitive": false}