{"public_metrics": {"retweet_count": 0, "reply_count": 0, "like_count": 0, "quote_count": 0}, "entities": {"mentions": [{"start": 0, "end": 6, "username": "pulte", "id": "25029495"}]}, "in_reply_to_user_id": "25029495", "text": "@pulte Yes because I know a few people who are more in need than I at this moment due to Coronavirus", "reply_settings": "everyone", "created_at": "2020-05-13T00:02:59.000Z", "source": "Twitter for iPhone", "context_annotations": [{"domain": {"id": "123", "name": "Ongoing News Story", "description": "Ongoing News Stories like 'Brexit'"}, "entity": {"id": "1220701888179359745", "name": "COVID-19"}}, {"domain": {"id": "29", "name": "Events [Entity Service]", "description": "Entity Service related Events domain"}, "entity": {"id": "1219057585707315201", "name": "COVID-19: Latest news updates from around the world", "description": "This page is a timeline of Tweets with the latest information and updates on COVID-19 from experts, journalists, health authorities and other trusted sources from around the world. For more on COVID-19, visit: twitter.com/explore/tabs/covid-19"}}], "author_id": "1107983111277723648", "referenced_tweets": [{"type": "replied_to", "id": "1260309281343225856"}], "id": "1260359849629626370", "lang": "en", "possibly_sensitive": false, "conversation_id": "1260309281343225856"}